## ------------------------------------------------------------------------------------ ##
## Preparation - set software paths
## ------------------------------------------------------------------------------------ ##
## Path to R binary and library, including arguments to R CMD BATCH
## Ex: R := R_LIBS=/home/Shared/Rlib/release-3.5-lib/ /usr/local/R/R-3.4.0/bin/R CMD BATCH --no-restore --no-save
## Ex: R := R CMD BATCH
R := R_LIBS=/home/bioinf/bioinf_data/43_sovi/R:/usr/local/lib/R/site-library:/usr/lib/R/site-library:/usr/lib/R/library R CMD BATCH --no-restore --no-save


## Path to Salmon binary
## Ex: salmon := /home/charlotte/software/Salmon-0.8.2_linux_x86_64/bin/salmon
salmon := salmon

## Path to FastQC binary
## Ex: fastqc := fastqc
fastqc := fastqc

## Path to TrimGalore! and cutadapt
## Ex: trimgalore := /home/charlotte/software/trim_galore_v0.4.4/trim_galore
## Ex: cutadapt := /home/charlotte/.local/bin/cutadapt
trimgalore := trim_galore
cutadapt :=  ~/.local/bin/cutadapt

## Path to STAR
## Ex: STAR := /home/Shared_penticton/software/STAR/source/STAR
STAR := STAR
Bowtie2 := bowtie2
## Path to samtools binary
## Ex: samtools := /usr/local/bin/samtools
samtools := samtools

## Path to MultiQC
## Ex: multiqc := multiqc
multiqc := multiqc

## Path to bedtools and the bedGraphToBigWig script
## Ex: bedtools := /usr/local/bin/bedtools
## Ex: bedGraphToBigWig := bedGraphToBigWig
bedtools := bedtools
bedGraphToBigWig := bedGraphToBigWig

## Path the sortmeRNA

sortmerna := sortmerna

## ------------------------------------------------------------------------------------ ##
## Preparation - set paths to reference files
## ------------------------------------------------------------------------------------ ##
## Path to existing genome fasta file
## Ex: genome := reference/genome/Danio_rerio.GRCz10.dna.toplevel.fa
genome := reference/Escherichia_coli_o157_h7_str_sakai.ASM886v1.dna.toplevel.fa


## Path to existing gtf file matching the genome fasta
## Ex: gtf := reference/gtf/Danio_rerio.GRCz10.87.gtf
gtf := reference/Escherichia_coli_o157_h7_str_sakai.ASM886v1.32.gtf

## Path to STAR genome index. Will be generated from the genome fasta file if it doesn't exist
## Ex: STARindex := reference/STARIndex/Danio_rerio.GRCz10.dna.toplevel
STARindex := STARindex/Escherichia_coli_o157_h7_str_sakai.ASM886v1.dna.toplevel
Bowtie2index := Bowtie2index/Escherichia_coli_o157_h7_str_sakai.ASM886v1.dna.toplevel

## Path to existing cDNA and ncRNA fasta files
## Ex: cdna := reference/cDNA/Danio_rerio.GRCz10.cdna.all.fa
## Ex: ncrna := reference/ncRNA/Danio_rerio.GRCz10.ncrna.fa
cdna := reference/Escherichia_coli_o157_h7_str_sakai.ASM886v1.cdna.all.fa
ncrna := reference/Escherichia_coli_o157_h7_str_sakai.ASM886v1.ncdna.all.fa

## Path to merged cDNA and ncRNA fasta file (will be generated by the script)
## Ex: txome := reference/Danio_rerio.GRCz10.cdna.ncrna.fa
txome := reference/Escherichia_coli_o157_h7_str_sakai.ASM886v1.ncdna.cdna.onlychr.fa

## Path to Salmon index. Will be generated from the merged cDNA and ncRNA fasta files if it doesn't exist
## Ex: salmonindex := reference/SalmonIndex/Danio_rerio.GRCz10.cdna.ncrna.sidx_0.8.2
salmonindex := reference/Escherichia_coli_o157_h7_str_sakai.ASM886v1.cdna.ncrna.sidx_0.8.2
## k-mer size for Salmon index
## Ex: salmonk := 31
salmonk := 23

## Path to rds file where the tx2gene mapping will be stored
## Ex: tx2gene := reference/SalmonIndex/Danio_rerio.GRCz10.cdna.ncrna_tx2gene.rds
tx2gene := reference/Escherichia_coli_o157_h7_str_sakai.ASM886v1.cdna.ncrna_tx2gene.rds

## Path to text file that will be generated to contain reference chromosome lengths
## Ex: chromlengthtxt := reference/Danio_rerio.GRCz10.chrlengths.txt
chromlengthtxt := reference/Escherichia_coli_o157_h7_str_sakai.ASM886v1.chrlengths.txt

## Path to rRNA.fasta database for sortmeRNA
##/home/bioinf/Downloads/sortmerna-2.1b/rRNA_databases/rfam5s_silva16s_silva23s_bac.fasta
rRNAdb := /home/bioinf/Downloads/sortmerna-2.1b/rRNA_databases/rfam5s_silva16s_silva23s_bac.fasta
rRNAdbindex := /home/bioinf/bioinf_data/43_sovi/Projects/Metagenomics_pipeline/Model_data/e_coli/04_trial_04/SortmeRNAindex/rfam5s_silva16s_silva23s_bac.idx


## ------------------------------------------------------------------------------------ ##
## Preparation - list files to process
## ------------------------------------------------------------------------------------ ##
## List sample IDs (should correspond to the FASTQ file names (excluding {_R1/2}.fastq.gz).
## Usually one of PEsamples or SEsamples is empty.
## Ex: SEsamples := S1 S2 S3
PEsamples :=
SEsamples := SRR2135666 SRR2135667 SRR2135672 SRR2135673 SRR2135678 SRR2135679
samples := $(PEsamples) $(SEsamples)

## Provide read length. This affects the generation of the STAR index
## Ex: readlength := 126
readlength := 50

## Path to metadata text file. This file must have at least one column, named "ID",
## containing the same values as the "samples" variable above.
## Ex: metatxt := metadata.txt
metatxt := metadata.txt

## Name of column in metadata text file that will be used to color coverage tracks and
## abundance values if results are explored with iResViewer
## Ex: groupvar := group
groupvar := time

## Number of cores (for FastQC, Salmon and STAR)
## Ex: ncores := 12
ncores := 8

.PHONY: all

## ------------------------------------------------------------------------------------ ##
## Target definition
## ------------------------------------------------------------------------------------ ##
## Run all analyses
all: MultiQC/multiqc_report.html output/shiny_results.rds output/shiny_results_edgeR.rds

## FastQC on original (untrimmed) files
runfastqc: $(foreach S,$(PEsamples),FastQC/$(S)_R1_fastqc.zip) \
$(foreach S,$(PEsamples),FastQC/$(S)_R2_fastqc.zip) \
$(foreach S,$(SEsamples),FastQC/$(S)_fastqc.zip)

## Trimming and FastQC on trimmed files
runtrimming: $(foreach S,$(PEsamples),FastQC/$(S)_R1_val_1_fastqc.zip) \
$(foreach S,$(PEsamples),FastQC/$(S)_R2_val_2_fastqc.zip) \
$(foreach S,$(SEsamples),FastQC/$(S)_trimmed_fastqc.zip)

runrrnaremoval: $(foreach S,$(SEsamples),FastQC/$(S)_trimmed_rrnaremoved_fastqc.zip)

## Salmon quantification
runsalmonquant: $(foreach S,$(samples),salmon/$(S)/quant.sf)

## STAR alignment
runstar: $(foreach S,$(samples),STAR/$(S)/$(S)_Aligned.sortedByCoord.out.bam.bai)

## STAR alignment
runbowtie2: $(foreach S,$(samples),Bowtie2/$(S)/$(S)_Aligned_bowtie.sortedByCoord.out.bam.bai)


## List all the packages that were used by the R analyses
listpackages:
	$(R) "--args Routdir='Rout' outtxt='R_package_versions.txt'" scripts/list_packages.R Rout/list_packages.Rout

## Print the versions of all software packages
softwareversions:
	$(R) --version
	$(salmon) --version
	$(trimgalore) --version
	$(cutadapt) --version
	$(fastqc) --version
	$(STAR) --version
	$(samtools) --version
	$(multiqc) --version
	$(bedtools) --version
	$(Bowtie2) --version
## ------------------------------------------------------------------------------------ ##
## Reference preparation
## ------------------------------------------------------------------------------------ ##
## Merge cDNA and ncRNA fasta files
$(txome): $(cdna) $(ncrna)
	mkdir -p $(@D)
	cat $(cdna) $(ncrna) > $@

## Generate Salmon index from merged cDNA and ncRNA files
$(salmonindex)/hash.bin: $(txome)
	mkdir -p $(@D)
	$(salmon) index -t $< -k $(salmonk) -i $(@D) --type quasi

## Generate tx2gene mapping
$(tx2gene): $(txome) scripts/generate_tx2gene.R
	mkdir -p $(@D)
	mkdir -p Rout
	$(R) "--args transcriptfasta='$(txome)' outrds='$@'" scripts/generate_tx2gene.R Rout/generate_tx2gene.Rout

## Generate STAR index
$(STARindex)/SA: $(genome) $(gtf)
	mkdir -p $(@D)
	$(STAR) --runMode genomeGenerate --runThreadN $(ncores) --genomeDir $(STARindex) \
	--genomeFastaFiles $(genome) --sjdbGTFfile $(gtf) --sjdbOverhang $(readlength)

## Generate bowtie2 index
$(Bowtie2index): $(genome) $(gtf)
	mkdir -p $(@D)
	$(Bowtie2)-build -t $(ncores) -f $(genome) $(Bowtie2index)

## Generate sortmeRNA database index index
$(rRNAdbindex): $(rRNAdb)
	mkdir -p $$(@D)
	indexdb_rna --ref $$<,$$@




## ------------------------------------------------------------------------------------ ##
## Quality control
## ------------------------------------------------------------------------------------ ##
## FastQC, original reads
define fastqcrule
FastQC/$(1)_fastqc.zip: FASTQ/$(1).fastq.gz
	mkdir -p $$(@D)
	$(fastqc) -o $$(@D) -t $(ncores) $$<
endef
$(foreach S,$(PEsamples),$(eval $(call fastqcrule,$(S)_R1)))
$(foreach S,$(PEsamples),$(eval $(call fastqcrule,$(S)_R2)))
$(foreach S,$(SEsamples),$(eval $(call fastqcrule,$(S))))

## FastQC, trimmed reads
define fastqcrule2
FastQC/$(1)_fastqc.zip: FASTQtrimmed/$(1).fq
	mkdir -p $$(@D)
	$(fastqc) -o $$(@D) -t $(ncores) $$<
endef
$(foreach S,$(PEsamples),$(eval $(call fastqcrule2,$(S)_R1_val_1)))
$(foreach S,$(PEsamples),$(eval $(call fastqcrule2,$(S)_R2_val_2)))
$(foreach S,$(SEsamples),$(eval $(call fastqcrule2,$(S)_trimmed)))

## FastQC, trimmed and rRNA removed reads
define fastqcrule3
FastQC/$(1)_fastqc.zip: SortmeRNA/$(1).fq
	mkdir -p $$(@D)
	$(fastqc) -o $$(@D) -t $(ncores) $$<
endef
$(foreach S,$(PEsamples),$(eval $(call fastqcrule3,$(S)_R1_val_rRNAremoved_1)))
$(foreach S,$(PEsamples),$(eval $(call fastqcrule3,$(S)_R2_val_rRNAremoved_2)))
$(foreach S,$(SEsamples),$(eval $(call fastqcrule3,$(S)_trimmed_rrnaremoved)))


MultiQC/multiqc_report.html: \
$(foreach S,$(PEsamples),FastQC/$(S)_R1_fastqc.zip) \
$(foreach S,$(PEsamples),FastQC/$(S)_R2_fastqc.zip) \
$(foreach S,$(SEsamples),FastQC/$(S)_fastqc.zip) \
$(foreach S,$(PEsamples),FastQC/$(S)_R1_val_1_fastqc.zip) \
$(foreach S,$(PEsamples),FastQC/$(S)_R2_val_2_fastqc.zip) \
$(foreach S,$(SEsamples),FastQC/$(S)_trimmed_fastqc.zip) \
$(foreach S,$(SEsamples),FastQC/$(S)_trimmed_rrnaremoved_fastqc.zip) \
$(foreach S,$(PEsamples),FASTQtrimmed/$(S)_R1_val_1.fq.gz) \
$(foreach S,$(PEsamples),FASTQtrimmed/$(S)_R2_val_2.fq.gz) \
$(foreach S,$(SEsamples),FASTQtrimmed/$(S)_trimmed.fq) \
$(foreach S,$(SEsamples),SortmeRNA/$(S)_trimmed_rrnaRemoved.fq) \
$(foreach S,$(samples),salmon/$(S)/quant.sf) \
$(foreach S,$(samples),STAR/$(S)/$(S)_Aligned.sortedByCoord.out.bam.bai)\
$(foreach S,$(samples),Bowtie2/$(S)/$(S)_Aligned_bowtie.sortedByCoord.out.bam.bai)
	mkdir -p $(@D)
	$(multiqc) FastQC FASTQtrimmed salmon STAR Bowtie2 -f -o $(@D)



## ------------------------------------------------------------------------------------ ##
## Adapter trimming
## ------------------------------------------------------------------------------------ ##
## TrimGalore!
define PEtrimrule
FASTQtrimmed/$(1)_R1_val_1.fq.gz: FASTQ/$(1)_R1.fastq.gz FASTQ/$(1)_R2.fastq.gz
	mkdir -p $$(@D)
	$(trimgalore) -q 20 --phred33 --length 20 -o $$(@D) --path_to_cutadapt $(cutadapt) \
	--paired $$(word 1,$$^) $$(word 2,$$^)
endef
$(foreach S,$(PEsamples),$(eval $(call PEtrimrule,$(S))))

define PEtrimrule2
FASTQtrimmed/$(1)_R2_val_2.fq.gz: FASTQtrimmed/$(1)_R1_val_1.fq.gz
endef
$(foreach S,$(PEsamples),$(eval $(call PEtrimrule2,$(S))))

define SEtrimrule
FASTQtrimmed/$(1)_trimmed.fq: FASTQ/$(1).fastq.gz
	mkdir -p $$(@D)
	$(trimgalore) -q 20 --phred33 --dont_gzip --length 20 -o $$(@D) --path_to_cutadapt $(cutadapt) \
	$$(word 1,$$^)
endef
$(foreach S,$(SEsamples),$(eval $(call SEtrimrule,$(S))))



## ------------------------------------------------------------------------------------ ##
## SortmeRNA removing of rRNA
## ------------------------------------------------------------------------------------ ##




define SEsortmeRNA
SortmeRNA/$(1)_trimmed_rrnaremoved.fq: FASTQtrimmed/$(1)_trimmed.fq
	mkdir -p $$(@D)
	mkdir -p SortmeRNA/rRNA
	$(sortmerna) --ref $(rRNAdb),$(rRNAdbindex) \
	--reads $$< --other SortmeRNA/$(1)_trimmed_rrnaremoved --log -v \
	--fastx --aligned SortmeRNA/rRNA/$(1)_aligned_rRNA_reads
endef
$(foreach S,$(SEsamples),$(eval $(call SEsortmeRNA,$(S))))


## ------------------------------------------------------------------------------------ ##
## Salmon abundance estimation
## ------------------------------------------------------------------------------------ ##
## Estimate abundances with Salmon
define PEsalmonrule
salmon/$(1)/quant.sf: $(salmonindex)/hash.bin \
FASTQtrimmed/$(1)_R1_val_1.fq.gz FASTQtrimmed/$(1)_R2_val_2.fq.gz
	mkdir -p $$(@D)
$(salmon) quant -i $$(word 1,$$(^D)) -l A -1 $$(word 2,$$^) -2 $$(word 3,$$^) \
	-o $$(@D) --gcBias --seqBias -p $(ncores)
endef
$(foreach S,$(PEsamples),$(eval $(call PEsalmonrule,$(S))))

define SEsalmonrule
salmon/$(1)/quant.sf: $(salmonindex)/hash.bin SortmeRNA/$(1)_trimmed_rrnaRemoved.fq
	mkdir -p $$(@D)
	$(salmon) quant -i $$(word 1,$$(^D)) -l A -r $$(word 2,$$^) \
	-o $$(@D) --seqBias -p $(ncores)
endef
$(foreach S,$(SEsamples),$(eval $(call SEsalmonrule,$(S))))

## ------------------------------------------------------------------------------------ ##
## STAR mapping
## ------------------------------------------------------------------------------------ ##
## Genome mapping with STAR
define PEstarrule
STAR/$(1)/$(1)_Aligned.sortedByCoord.out.bam: $(STARindex)/SA \
FASTQtrimmed/$(1)_R1_val_1.fq.gz FASTQtrimmed/$(1)_R2_val_2.fq.gz
	mkdir -p $$(@D)
	$(STAR) --genomeDir $(STARindex) \
	--readFilesIn $$(word 2,$$^) $$(word 3,$$^) \
	--runThreadN $(ncores) --outFileNamePrefix $$(@D)/$(1)_ \
	--outSAMtype BAM SortedByCoordinate --readFilesCommand gunzip -c --seedPerWindowNmax 100
endef
$(foreach S,$(PEsamples),$(eval $(call PEstarrule,$(S))))



define SEstarrule
STAR/$(1)/$(1)_Aligned.sortedByCoord.out.bam: $(STARindex)/SA SortmeRNA/$(1)_trimmed_rrnaRemoved.fq
	mkdir -p $$(@D)
	$(STAR) --genomeDir $(STARindex) \
	--readFilesIn $$(word 2,$$^) \
	--runThreadN $(ncores) --outFileNamePrefix $$(@D)/$(1)_ \
	--outSAMtype BAM SortedByCoordinate
endef
$(foreach S,$(SEsamples),$(eval $(call SEstarrule,$(S))))



## Index bam files
define starindexrule
STAR/$(1)/$(1)_Aligned.sortedByCoord.out.bam.bai: STAR/$(1)/$(1)_Aligned.sortedByCoord.out.bam
	$(samtools) index $$<
endef
$(foreach S,$(samples),$(eval $(call starindexrule,$(S))))

## Get chromosome lengths
$(chromlengthtxt): STAR/$(word 1,$(samples))/$(word 1,$(samples))_Aligned.sortedByCoord.out.bam
	$(samtools) view -H $< | grep '@SQ' | cut -f2,3 | sed -e 's/SN://' | sed -e 's/LN://' > $@

## Convert BAM files to bigWig
define bigwigrule
STARbigwig/$(1)_Aligned.sortedByCoord.out.bw: $(chromlengthtxt) STAR/$(1)/$(1)_Aligned.sortedByCoord.out.bam
	mkdir -p $$(@D)
	$(bedtools) genomecov -split -ibam $$(word 2,$$^) -bg > $$(@D)/$(1)_Aligned.sortedByCoord.out.bedGraph
	$(bedGraphToBigWig) $$(@D)/$(1)_Aligned.sortedByCoord.out.bedGraph $$(word 1,$$^) $$@
	rm -f $$(@D)/$(1)_Aligned.sortedByCoord.out.bedGraph
endef
$(foreach S,$(samples),$(eval $(call bigwigrule,$(S))))

## ------------------------------------------------------------------------------------ ##
## bowtie2 mapping
## ------------------------------------------------------------------------------------ ##

define SEbowtie2rule
Bowtie2/$(S)/$(S)_Aligned_bowtie.sortedByCoord.out.sam: $(Bowtie2index) SortmeRNA/$(1)_trimmed_rrnaRemoved.fq
	mkdir -p $$(@D)
	$(Bowtie2) --end-to-end --no-unal -p $(ncores) \
	-t -x $(Bowtie2index) -U $$(word 2,$$^) \
	-S $$@
endef
$(foreach S,$(SEsamples),$(eval $(call SEbowtie2rule,$(S))))

define SEsort
Bowtie2/$(S)/$(S)_Aligned_bowtie.sortedByCoord.out.bam: Bowtie2/$(S)/$(S)_Aligned_bowtie.sortedByCoord.out.sam
	$(samtools) sort -m 10737418240 -O BAM $$< -o $$@
endef
$(foreach S,$(SEsamples),$(eval $(call SEsort,$(S))))

##define SEsam2bam
##Bowtie2/$(S)/$(S)_Aligned_bowtie.sortedByCoord.out.bam: Bowtie2/$(S)/$(S)_Aligned_bowtie.sortedByCoord.out_sort.sam
##	$(samtools) view -bS -o $$@ $$<
##endef
##$(foreach S,$(SEsamples),$(eval $(call SEsam2bam,$(S))))

## Index bam files
define bowtie2indexrule
Bowtie2/$(S)/$(S)_Aligned_bowtie.sortedByCoord.out.bam.bai: Bowtie2/$(S)/$(S)_Aligned_bowtie.sortedByCoord.out.bam
	$(samtools) index $$<
endef
$(foreach S,$(samples),$(eval $(call bowtie2indexrule,$(S))))


## Convert BAM files to bigWig
define bigwigbowtie2rule
Bowtie2bigwig/$(1)_Aligned_bowtie.sortedByCoord.out.bw: $(chromlengthtxt) Bowtie2/$(S)/$(S)_Aligned_bowtie.sortedByCoord.out.bam
	mkdir -p $$(@D)
	$(bedtools) genomecov -split -ibam $$(word 2,$$^) -bg > $$(@D)/$(1)_Aligned_bowtie.sortedByCoord.out.bedGraph
	$(bedGraphToBigWig) $$(@D)/$(1)_Aligned_bowtie.sortedByCoord.out.bedGraph $$(word 1,$$^) $$@
	rm -f $$(@D)/$(1)_Aligned_bowtie.sortedByCoord.out.bedGraph
endef
$(foreach S,$(samples),$(eval $(call bigwigbowtie2rule,$(S))))


## ------------------------------------------------------------------------------------ ##
## Differential expression
## ------------------------------------------------------------------------------------ ##
## edgeR
output/edgeR_dge.rds: $(tx2gene) $(metatxt) scripts/run_dge_edgeR.R \
$(foreach S,$(samples),salmon/$(S)/quant.sf)
	mkdir -p output
	mkdir -p Rout
	mkdir -p diagnosticPlots
	$(R) "--args tx2gene='$<' salmondir='salmon' outrds='$@' metafile='$(metatxt)'" scripts/run_dge_edgeR.R Rout/run_dge_edgeR.Rout

## ------------------------------------------------------------------------------------ ##
## Shiny app
## ------------------------------------------------------------------------------------ ##
output/shiny_results.rds: output/edgeR_dge.rds $(gtf) $(tx2gene) $(metatxt) \
scripts/prepare_results_for_shiny.R \
$(foreach S,$(samples),Bowtie2bigwig/$(S)_Aligned_bowtie.sortedByCoord.out.bw)
	mkdir -p output
	mkdir -p Rout
	$(R) "--args edgerres='output/edgeR_dge.rds' groupvar='$(groupvar)' gtffile='$(gtf)' tx2gene='$(tx2gene)' metafile='$(metatxt)' bigwigdir='Bowtie2bigwig' outrds='$@'" scripts/prepare_results_for_shiny.R Rout/prepare_results_for_shiny.Rout

output/shiny_results_edgeR.rds: output/edgeR_dge.rds $(tx2gene) $(metatxt) \
scripts/prepare_results_for_shiny.R
	mkdir -p output
	mkdir -p Rout
	$(R) "--args edgerres='output/edgeR_dge.rds' groupvar='$(groupvar)' gtffile=NULL tx2gene='$(tx2gene)' metafile='$(metatxt)' bigwigdir=NULL outrds='$@'" scripts/prepare_results_for_shiny.R Rout/prepare_results_for_shiny_edgeR.Rout
